pluginManagement {
    repositories {
        google()
        mavenCentral()
//        maven { url = uri("https://oss.sonatype.org/content/repositories/snapshots") }
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io'}    }
//        maven { url = uri("https://oss.sonatype.org/content/repositories/snapshots") }
}

rootProject.name = "Diary"
include ':app'
include ':core:ui'
include ':core:util'
include ':data:mongo'
include ':feature:auth'
include ':feature:home'
include ':feature:write'
